-- ============================================================
-- 024e – Seed the standard set of job-title designations
--
-- 91 unique designations covering every role HR currently has on
-- their PolyTech roster, plus the small HR/admin subset already
-- in use. The list HR supplied had a few whitespace artefacts
-- (trailing spaces on "Equipment Planner ", "Estimator ", etc.)
-- and one duplicate ("Safety & BA Officer" listed twice); both
-- have been canonicalised away.
--
-- One known typo retained as-supplied: "Manager- Estmation & PMO"
-- (should be "Estimation"). When HR confirms the correction we
-- can rename via ON UPDATE CASCADE — every profile referencing
-- the old value follows automatically because of the FK.
-- ============================================================

INSERT INTO public.lookup_designations (name) VALUES
  ('Accountant'),
  ('Administrator'),
  ('Asset and AP Supervisor'),
  ('Auto Electrician'),
  ('BD Admin Officer'),
  ('Buyer'),
  ('Chemical Technician'),
  ('Chemist'),
  ('Cost Analyst'),
  ('Credit & Collection Team Leader'),
  ('DEPUTY GENERAL MANAGER'),
  ('Deputy Manager-GR'),
  ('Diesel Mechanic'),
  ('Driver - Admin'),
  ('Driver - Bahrain'),
  ('Driver - HD'),
  ('Dy. General Manager (Operations)'),
  ('Electrical Technician'),
  ('Electrical Technician II'),
  ('Engineer'),
  ('Equipment Planner'),
  ('Equipment Supervisor'),
  ('Estimator'),
  ('Facility Technician'),
  ('FINANCE MANAGER'),
  ('Fire Watch'),
  ('Foreman'),
  ('Foreman/WPR'),
  ('Forklift Operator'),
  ('General Fitter'),
  ('Government Rep - I'),
  ('GRO-ID'),
  ('H.D.Driver/SS Operator'),
  ('Heavy Duty Mechanic'),
  ('Helper'),
  ('Helper - Mechanical'),
  ('HR & Admin Director'),
  ('HR / Admin Officer'),
  ('Hydrojetter'),
  ('ID Officer'),
  ('Jr. Estimator'),
  ('Jr. Planning Engineer'),
  ('Jr. Supervisor'),
  ('Jr.Engineer'),
  ('Lead Technician'),
  ('Logistics Officer'),
  ('Maintenance Assistant'),
  ('Maintenance Team Leader'),
  ('Manager- Estmation & PMO'),
  ('Manpower ID Receiver'),
  ('Manpower ID Supervisor'),
  ('Mechanic'),
  ('Mechanic /HVD'),
  ('Mechanical Fitter'),
  ('Mechanical Foreman'),
  ('Mechanical Helper'),
  ('Messenger / Office Boy'),
  ('Metal Fabricator'),
  ('Office Boy'),
  ('Pipefitter'),
  ('Procurement Officer'),
  ('Project Administrator'),
  ('Project Coordinator'),
  ('Project Engineer'),
  ('Project Lead'),
  ('Project Manager'),
  ('Rigger II'),
  ('Rigger III'),
  ('Safety & BA Officer'),
  ('Safety Engineer'),
  ('Safety Manager'),
  ('Safety Officer'),
  ('Safety Supervisor'),
  ('Sales Executive'),
  ('Security Guard'),
  ('Security Man'),
  ('Security Supervisor'),
  ('Site Engineer'),
  ('Site Supervisor'),
  ('Site Supervisor - BP/Mechanical'),
  ('Sr. HR Generalist'),
  ('Sr. Safety Supervisor'),
  ('Sr.Foreman'),
  ('Store Keeper'),
  ('Supervisor'),
  ('System Administrator'),
  ('Technician'),
  ('Timekeeper'),
  ('Welder'),
  ('Work Permit Receiver'),
  ('WPR/Mechanical Foreman')
ON CONFLICT (name) DO NOTHING;
